server:
  port: 8761

spring:
  application:
    name: service-registry
  cloud:
    config:
      enabled: false

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"