server:
  port: 8084

spring:
  application:
    name: order-service
  devtools:
    restart:
      enabled: true
  data:
    cassandra:
      contact-points: ${SPRING_CASSANDRA_CONTACT_POINTS}
      port: ${SPRING_CASSANDRA_PORT}
      keyspace-name: ${SPRING_CASSANDRA_KEYSPACE}
      local-datacenter: datacenter1
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}