server:
  port: 8083

spring:
  application:
    name: item-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}